services:
  postgres:
    image: debezium/example-postgres:2.5 # Use the Debezium-ready image
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog

  kafka:
    image: quay.io/debezium/kafka:2.5
    ports:
      - "9092:9092"
    environment:
      - CLUSTER_ID=nexus-cluster
      - NODE_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  connect:
    image: quay.io/debezium/connect:2.5
    ports:
      - "8183:8183"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - postgres