spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/catalog
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          fetch_size: 50
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    function:
      definition: productEventSupplier
    stream:
      bindings:
        productEventSupplier-out-0:
          destination: catalog.product.events
          producer:
            partition-count: 2
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        bindings:
          productEventSupplier-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://your-auth-server/realms/nexus # Replace with your Actual Auth Server URL
  springdoc:
    writer-with-json-view: true
    model-and-view-allowed: true
    show-actuator: false
    default-produces-media-type: application/json
    group-configs:
      - group: 'Catalog API'
        paths-to-match: /v1/**
    api-docs:
      enabled: true
      swagger-ui:
        enabled: true
    open-api:
      info:
        title: "Nexus Catalog"
        version: "v1"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-admin:discovery-secure-password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30