spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/catalog
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: true
        jdbc:
          fetch_size: 50
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    stream:
      source: publish
      bindings:
        publish-out-0:
          destination: product
          producer:
            partition-count: 3
      kafka:
        binder:
          brokers: localhost:29092
          auto-create-topics: true
          min-partition-count: 3
          replication-factor: 1
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://your-auth-server/realms/nexus
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-admin:discovery-secure-password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30