server:
  port: 8888

spring:
  application:
    name: config
  security:
    user:
      name: config-admin
      password: config-secure-password
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configurations/common
            - classpath:/configurations/dev
            - classpath:/configurations/prod
