-- liquibase formatted sql

-- changeset Uvindu:1777052988919-1
CREATE TABLE brand
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    website      VARCHAR(255),
    logo_url     VARCHAR(255),
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

-- changeset Uvindu:1777052988919-2
CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    slug      VARCHAR(255)                            NOT NULL,
    parent_id BIGINT,
    is_active BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset Uvindu:1777052988919-3
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(50)                             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2)                          NOT NULL,
    status      VARCHAR(20)                             NOT NULL,
    brand_id    BIGINT,
    category_id BIGINT,
    version     INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset Uvindu:1777052988919-4
CREATE TABLE product_attribute
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    value      VARCHAR(255)                            NOT NULL,
    product_id BIGINT,
    CONSTRAINT pk_productattribute PRIMARY KEY (id)
);

-- changeset Uvindu:1777052988919-5
ALTER TABLE brand
    ADD CONSTRAINT uc_brand_name UNIQUE (name);

-- changeset Uvindu:1777052988919-6
ALTER TABLE brand
    ADD CONSTRAINT uc_brand_website UNIQUE (website);

-- changeset Uvindu:1777052988919-7
ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

-- changeset Uvindu:1777052988919-8
ALTER TABLE category
    ADD CONSTRAINT uc_category_slug UNIQUE (slug);

-- changeset Uvindu:1777052988919-9
ALTER TABLE product
    ADD CONSTRAINT uc_product_code UNIQUE (code);

-- changeset Uvindu:1777052988919-10
ALTER TABLE product
    ADD CONSTRAINT uc_product_slug UNIQUE (slug);

-- changeset Uvindu:1777052988919-11
ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_PARENT FOREIGN KEY (parent_id) REFERENCES category (id);

-- changeset Uvindu:1777052988919-12
ALTER TABLE product_attribute
    ADD CONSTRAINT FK_PRODUCTATTRIBUTE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

-- changeset Uvindu:1777052988919-13
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id);

-- changeset Uvindu:1777052988919-14
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

