-- liquibase formatted sql

-- changeset nexus:001-01 labels:init
CREATE TABLE brand
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    website      VARCHAR(255),
    logo_url     VARCHAR(255),
    active       BOOLEAN                                 NOT NULL DEFAULT true,
    created_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_brand PRIMARY KEY (id),
    CONSTRAINT uc_brand_name UNIQUE (name),
    CONSTRAINT uc_brand_website UNIQUE (website)
);

-- changeset nexus:001-02 labels:init
CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    slug      VARCHAR(255)                            NOT NULL,
    parent_id BIGINT,
    active    BOOLEAN                                 NOT NULL DEFAULT true,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uc_category_name UNIQUE (name),
    CONSTRAINT uc_category_slug UNIQUE (slug),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id)
);

-- changeset nexus:001-03 labels:init
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(50)                             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2)                          NOT NULL,
    status      VARCHAR(20)                             NOT NULL,
    brand_id    BIGINT,
    category_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT uc_product_sku UNIQUE (sku),
    CONSTRAINT uc_product_slug UNIQUE (slug),
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand (id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- changeset nexus:001-04 labels:init
CREATE TABLE product_attribute
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    value      VARCHAR(255)                            NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_attribute PRIMARY KEY (id),
    CONSTRAINT fk_product_attribute_product FOREIGN KEY (product_id) REFERENCES product (id)
);

-- changeset nexus:001-05 labels:init
CREATE TABLE outbox
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(100) NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_outbox PRIMARY KEY (id)
);

-- changeset nexus:001-06 labels:init
CREATE TABLE outbox_archive
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(100) NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(50)  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    archived_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_outbox_archive PRIMARY KEY (id)
);

-- changeset nexus:001-07 labels:init
-- comment: FK indexes — PostgreSQL does not auto-index foreign key columns
CREATE INDEX idx_category_parent_id ON category (parent_id);
CREATE INDEX idx_product_brand_id ON product (brand_id);
CREATE INDEX idx_product_category_id ON product (category_id);
CREATE INDEX idx_product_attribute_product_id ON product_attribute (product_id);

-- changeset nexus:001-08 labels:init
-- comment: Query-pattern indexes
CREATE INDEX idx_product_status ON product (status);
CREATE INDEX idx_product_attribute_key ON product_attribute (key);

-- changeset nexus:001-09 labels:init
-- comment: Partial indexes for outbox schedulers — each covers exactly one status value
CREATE INDEX idx_outbox_pending ON outbox (created_at) WHERE status = 'PENDING';
CREATE INDEX idx_outbox_processed ON outbox (created_at) WHERE status = 'PROCESSED';