-- liquibase formatted sql

-- changeset Uvindu:1778061605290-1
CREATE TABLE inbox
(
    id                UUID         NOT NULL,
    aggregate_type    VARCHAR(255) NOT NULL,
    aggregate_id      VARCHAR(255) NOT NULL,
    type              VARCHAR(255) NOT NULL,
    payload           JSONB        NOT NULL,
    status            VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    processed_at      TIMESTAMP WITHOUT TIME ZONE,
    retry_count       INTEGER      NOT NULL,
    last_attempted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inbox PRIMARY KEY (id)
);

-- changeset Uvindu:1778061605290-2
CREATE TABLE inbox_archive
(
    id             UUID         NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    archived_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inboxarchive PRIMARY KEY (id)
);

-- changeset Uvindu:1778061605290-3
CREATE TABLE stock
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    available_quantity INTEGER                                 NOT NULL,
    reserved_quantity  INTEGER                                 NOT NULL,
    version            INTEGER                                 NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

-- changeset Uvindu:1778061605290-4
CREATE TABLE stock_reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stockreservation PRIMARY KEY (id)
);

-- changeset Uvindu:1778061605290-5
ALTER TABLE stock
    ADD CONSTRAINT uq_stock_product_id UNIQUE (product_id);

-- changeset Uvindu:1778061605290-6
CREATE INDEX idx_stock_reservation_product_status ON stock_reservation (product_id, status);
CREATE INDEX idx_stock_reservation_order_status ON stock_reservation (order_id, status);

-- changeset Uvindu:1778061605290-7
CREATE INDEX idx_stock_reservation_expires_at_active
    ON stock_reservation (expires_at)
    WHERE status = 'ACTIVE';

-- changeset Uvindu:1778061605290-8
CREATE INDEX idx_inbox_status_retry ON inbox (status, retry_count);
CREATE INDEX idx_inbox_aggregate_id ON inbox (aggregate_id);
CREATE INDEX idx_inbox_status_created_at ON inbox (status, created_at);

-- changeset Uvindu:1778061605290-9
CREATE INDEX idx_inbox_archive_aggregate_id ON inbox_archive (aggregate_id);
CREATE INDEX idx_inbox_archive_archived_at ON inbox_archive (archived_at);
