nexus:
  messaging:
    bindings:
      product-out: productEventSupplier-out-0
server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true
  management:
    endpoints:
      web:
        base-path: /actuator # Default, but can be changed to /manage for security obfuscation
        exposure:
          include: health, info, metrics, prometheus, loggers
    endpoint:
      health:
        show-details: when_authorized # Only shows DB/Disk details to authenticated users
        probes:
          enabled: true # Essential for Kubernetes Liveness/Readiness probes
      metrics:
        enabled: true
    observations:
      key-values:
        application: project-nexus # Tags all metrics for easy filtering in Grafana
